<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
<!--
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
-->
    <TargetFramework>netstandard2.0</TargetFramework>

    <Nullable>disable</Nullable>
    <AssemblyTitle>Ionic's Zip Library</AssemblyTitle>
    <AssemblyName>Ionic.Zip</AssemblyName>

    <PackageId>DotNetZip.Original</PackageId>
    <Version>2025.02.15</Version>
    <Authors>Dino Chiesa</Authors>
    <Company>Dino Chiesa</Company>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="\"/>
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\CommonSrc\CRC32.cs">
      <Link>CRC32.cs</Link>
    </Compile>
    <Compile Include="..\CommonSrc\StreamExtensions.ReadExactly.cs">
      <Link>StreamExtensions.ReadExactly.cs</Link>
    </Compile>
    <Compile Include="..\BZip2\*.cs">
      <Link>BZip2\%(FileName)</Link>
    </Compile>
    <Compile Include="..\Zlib\*.cs">
      <Link>Zlib\%(FileName)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="9.0.1" />
    <PackageReference Include="System.Security.Permissions" Version="9.0.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.1" />
  </ItemGroup>

</Project>
